version: "3.8"

services:
  backend:
    container_name: backend
    build:
      dockerfile: packages/backend/Dockerfile
      context: .
      target: dev
    env_file:
      - ./.env
    restart: always
    volumes:
      - ./packages/backend/:/usr/src/app
      - /usr/src/app/node_modules/
    depends_on:
      - db
      - clickhouse
    ports:
      - "3170:3170"

  db:
    image: postgres:latest
    container_name: postgres_db
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "sh -c 'pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}'",
        ]
      interval: 5s
      timeout: 5s
      retries: 10

  clickhouse:
    image: "clickhouse/clickhouse-server:${CLICKHOUSE_VERSION-23.2-alpine}"
    container_name: clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    healthcheck:
      # "clickhouse", "client", "-u ${CLICKHOUSE_USER}", "--password ${CLICKHOUSE_PASSWORD}", "-q 'SELECT 1'"
      test: ["CMD", "wget", "--spider", "-q", "localhost:8123/ping"]
      interval: 30s
      timeout: 5s
      retries: 3
    volumes:
      - "./.docker/clickhouse/config.xml:/etc/clickhouse-server/config.xml"
      - "./.docker/clickhouse/users.xml:/etc/clickhouse-server/users.xml"

volumes:
  postgres_data:
